#
# This file is part of LiteDRAM.
#
# Copyright (c) 2023 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: BSD-2-Clause

# Python
import logging
# migen
from migen import *
from migen.fhdl import verilog
# Litex
from litedram.DDR5RCD01.RCD_definitions import *
from litedram.DDR5RCD01.RCD_interfaces import *
from litedram.DDR5RCD01.RCD_interfaces_external import *
from litedram.DDR5RCD01.RCD_utils import *


class DDR5RCD01Alert(Module):
    """
    DDR5 RCD01 Alert
    ----------------

    The alert_n signal is generated by this module based on responses from:
        - parity error checkers in channels


        - error statuses in RWs

    The shape of the alert_n signal is controlled by RWs.

    The alert_n signal assertion from pairty errors can be:
        - static

        - pulsed
        Pulse width is regulated by table 100
        If both channels assert error, then the pulse is overlapping (reset counter)

    alert_n stays on until "Clear CA Parity Error" Command is setn.

    If derror_in_n is asserted, then alert_n is asserted as well, except:
        - DRST_n is asserted

        - the device is in clock stopped power down mode


    Module
    ------
    d - Input : data
    q - Output: data
    ------
    """

    def __init__(self,
                 if_ck_rst,
                 if_channel_common_A,
                 if_channel_common_B,
                 if_alert_n,
                 if_ctrl_common,
                 if_config_common,
                 ):
        # TODO take errors from channel and create a pulse
        # TODO implement control
        # TODO Implementation forces no error

        # inputs
        """
            Table 100 - ALERT_n Pulse Width for Parity Error
            Name | Min | Max

        """
        PULSE_WIDTH_DICT = {
            "DEBUG": {"MIN": 5, "MAX": 7},
            "DDR5-3200": {"MIN": 96, "MAX": 192},
            "DDR5-3600": {"MIN": 108, "MAX": 216},
            "DDR5-4000": {"MIN": 120, "MAX": 240},
            "DDR5-4400": {"MIN": 132, "MAX": 264},
            "DDR5-4800": {"MIN": 144, "MAX": 288},
        }
        # PULSE_WIDTH = PULSE_WIDTH_DICT["DDR5-3200"]["MIN"]
        PULSE_WIDTH = PULSE_WIDTH_DICT["DEBUG"]["MIN"]
        logging.debug("Set PULSE WIDTH = " + str(PULSE_WIDTH))

        self.comb += if_alert_n.alert_n.eq(1)

        # Ignore drst_n

        # Handle error from SDRAM
        # Highest priority
        # HARD-CODE 16 (meant fosr width of 288)
        pulse_width_counter = Signal(16)

        is_high_priority_error_asserted = Signal()
        self.comb += If(
            (if_channel_common_A.err_n_sdram == 0) |
            (if_channel_common_B.err_n_sdram == 0),
            if_alert_n.alert_n.eq(0),
            is_high_priority_error_asserted.eq(1),
        ).Else(
            If(
                (pulse_width_counter > 0),
                if_alert_n.alert_n.eq(0),
                is_high_priority_error_asserted.eq(0)
            )
        )

        # Parity errors
        start_alert = Signal()
        self.sync += If(
            ~is_high_priority_error_asserted,
            If(
                if_channel_common_A.err_parity | if_channel_common_B.err_parity,
                start_alert.eq(1),
            ).Else(
                start_alert.eq(0),
            )
        )

        self.sync += If(
            start_alert,
            pulse_width_counter.eq(PULSE_WIDTH)
        ).Else(
            If(
                pulse_width_counter != 0,
                pulse_width_counter.eq(pulse_width_counter-1),
            )
        )


class TestBed(Module):
    def __init__(self):
        self.if_ck_rst = If_ck_rst()
        self.if_channel_common_A = If_channel_common()
        self.if_channel_common_B = If_channel_common()
        self.if_alert_n = If_alert_n()
        self.if_ctrl_common = If_ctrl_common()
        self.if_config_common = If_config_common()

        self.submodules.dut = DDR5RCD01Alert(
            if_ck_rst=self.if_ck_rst,
            if_channel_common_A=self.if_channel_common_A,
            if_channel_common_B=self.if_channel_common_B,
            if_alert_n=self.if_alert_n,
            if_ctrl_common=self.if_ctrl_common,
            if_config_common=self.if_config_common,
        )


def run_test(tb):
    logging.debug('Write test')
    yield tb.if_channel_common_A.err_parity.eq(0)
    yield tb.if_channel_common_A.err_n_sdram.eq(1)
    yield tb.if_channel_common_B.err_parity.eq(0)
    yield tb.if_channel_common_B.err_n_sdram.eq(1)
    for i in range(2):
        yield
    yield tb.if_channel_common_A.err_n_sdram.eq(0)
    for i in range(3):
        yield
    yield tb.if_channel_common_A.err_n_sdram.eq(1)
    for i in range(1):
        yield
    yield tb.if_channel_common_A.err_parity.eq(1)
    yield
    yield tb.if_channel_common_A.err_parity.eq(0)
    for i in range(2):
        yield
    yield tb.if_channel_common_B.err_parity.eq(1)
    yield
    yield tb.if_channel_common_B.err_parity.eq(0)
    for i in range(10):
        yield

    logging.debug('Yield from write test.')


if __name__ == "__main__":
    eT = EngTest()
    logging.info("<- Module called")
    tb = TestBed()
    logging.info("<- Module ready")
    run_simulation(tb, run_test(tb), vcd_name=eT.wave_file_name)
    logging.info("<- Simulation done")
    logging.info(str(eT))
